version: "3.7"

services:

  client:
    build: ./Client
    container_name: cliente
    depends_on:
      - db
      - server
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://cache

  server:
    build: ./Server
    container_name: servidor
    depends_on:
      - db
      - cache
    environment:
      - REDIS_URL=redis://cache

  redis:
    image: bitnami/redis:6.0.16
    command: ["redis-server", "--bind", "redis_sv","--maxmemory 2mb","--maxmemory-policy allkeys-lru"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    ports:
      - "6379:6379"
  
  
  db:
    image: docker.io/bitnami/postgresql:11
    hostname: myhost
    environment:
      - POSTGRES_DB= juan
      - POSTGRES_USER= a
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_PASSWORD= a
    
    volumes:
      - ./Postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      
    ports:
      - "9091:5432"
  
  grpc-server:
    build: ./GRPC
    restart: always
    ports: 
      - "8050:8050"
    depends_on:
      - server
      - client

