version: "3.7"

services:
  app:
    image: testport
    ports:
      - "3000:3000"
  
  redis:
    image: bitnami/redis:6.0.16
    restart: always
    command: ["redis-server", "--bind", "redis_sv","--maxmemory 2mb","--maxmemory-policy allkeys-lru"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  
  db:
    image: postgres:14.2
    restart: always
    hostname: myhost
    environment:
      POSTGRES_DB: juan
      POSTGRES_USER: a
      POSTGRES_PASSWORD: a
    
    volumes:
      - /Documentos/T1/postgres:/var/lib/postgresql/data
      - ./Postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      
    ports:
      - "9091:5432"
  
  grpc-server:
    build: ./GRPC
    restart: always
    ports: 
      - "8050:8050"
    depends_on:
      - server
      - client

  client:
    build: ./Client
    depends_on:
      - postgres
      - server
    ports:
      - "8080:8080"

  server:
    build: ./Server
    depends_on:
      - postgres